# Generated by Django 6.0 on 2026-01-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umutdizmancom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="package",
            field=models.CharField(
                choices=[
                    ("starter", "Starter"),
                    ("business", "Business"),
                    ("pro", "Pro"),
                    ("consult", "Not sure yet"),
                ],
                default="consult",
                max_length=20,
            ),
        ),
    ]
